In [1]:
import numpy as np

# EX1

In [2]:
a=np.array([[1,2,3,3,1],[6,8,11,10,7]])
print(a)

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]


In [3]:
mean_a=[np.mean(a[0])],[np.mean(a[1])]
print(mean_a)

([2.0], [8.4])


# EX2

In [4]:
a_centered=a-mean_a
print(a_centered)

[[-1.   0.   1.   1.  -1. ]
 [-2.4 -0.4  2.6  1.6 -1.4]]


# EX3

In [5]:
a_centered_sp=np.dot(a_centered[0],a_centered[1])
print(a_centered_sp)

8.0


In [6]:
print(a_centered_sp/(len(a_centered)-1))

8.0


# ex4

In [7]:
a_tr=a.transpose()
print(a_tr)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


### а почему значение коварииации будет равно элементу в строке 0 с индексом 1? это же 2 я так понимаю? или же как в транспонированной 15 ( второй элемент первой строки) непонятен этот момент

In [8]:
print(np.cov(a))

[[1.  2. ]
 [2.  4.3]]


In [9]:
print(np.cov(a_tr))

[[12.5 15.  20.  17.5 15. ]
 [15.  18.  24.  21.  18. ]
 [20.  24.  32.  28.  24. ]
 [17.5 21.  28.  24.5 21. ]
 [15.  18.  24.  21.  18. ]]


# pandas1

In [10]:
import pandas as pd

In [11]:
authors=pd.DataFrame({'author_id':[1,2,3],
     'author_name':["Тургенев","Чехов","Островский"]})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

### по моему же как то еще можно было эффективным способом создать фрейм без присваивания в переменную

In [12]:
books=pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                    'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                    'price':[450, 300, 350, 500, 450, 370, 290]},columns=['author_id','book_title','price'])
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

# pandas2

In [13]:
authors_price=pd.merge(authors,books)
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

# pandas3

In [14]:
top5=authors_price.sort_values('price',ascending=False).head(5)
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

# Pnadas4

In [15]:
authors_stat=authors_price.groupby('author_name').agg(maxprice=('price','max'),minprice=('price','min'),meanprice=('price','mean'))
authors_stat

maxprice  minprice   meanprice
author_name                                
Островский        370       290  330.000000
Тургенев          450       300  366.666667
Чехов             500       450  475.000000

# pandas 5

In [16]:
authors_price['cover']=['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [17]:
?pd.pivot_table

In [26]:
book_info=pd.pivot_table(authors_price,index=['author_name'],columns=['cover'],fill_value=1)
book_info.to_pickle('book_info.pkl')

In [27]:
book_info2=pd.read_pickle('book_info.pkl')
book_info2==book_info

author_id          price        
cover          мягкая твердая мягкая твердая
author_name                                 
Островский       True    True   True    True
Тургенев         True    True   True    True
Чехов            True    True   True    True